### ISSUE TITLE
No progress bar when using parallel option

### ISSUE THREAD

**Issue by bobmuscarella** [bobmuscarella/ENMeval#10]
I do think we should remove the 'updateprogress' argument in the release version AND add some default progress bar for the parallel option.  The original one for the non-parallel version works fine but I don't know how to make one for parallel... do you?

**Comment by ndimhypervol** [comment]
Hmm. I looked into it and it seems pretty difficult, if not outright impossible to put up a progress bar on the command line while running parallel. The way I have it set up, where it writes progress to a file, I got from stackoverflow. I was thinking we could provide more useful timing stats in that file instead of just write each step of the progress bar.

**Comment by bobmuscarella** [comment]
In case you didn't see this, check the link below for an example progress bar with foreach.  I'm not sure it will work in the ENMeval code, though...  

http://stackoverflow.com/questions/5423760/how-do-you-create-a-progress-bar-when-using-the-foreach-function-in-r

If we can't get it to work, we may have to just write out a message that says something like, "Running parallel analysis..."

**Comment by bobmuscarella** [comment]
Forget about progress bar, just put message saying, "working" and then report time when done.
