### ISSUE TITLE
no slot of name "models" 

### ISSUE THREAD

**Issue by elgabbas** [bobmuscarella/ENMeval#32]
Hello All,
I have a problem with accessing an ENMevaluate object created with a previous version of ENMeval. In previous version, there was no possibility to keep the model objects. Now when I use the `str` function to access the contents I get this error: 
`Error in FUN(X[[i]], ...) : no slot of name "models" for this object of class "ENMevaluation"`

Cheers,
Ahmed

**Comment by bobmuscarella** [comment]
Hi Ahmed -
Yes, if I understand you correctly, the issue is that ENMevaluate objects created with versions of ENMeval *before* v 0.2.0 did **not** include the model objects.  You therefore cannot access them (as they were never stored) and to get them you need to re-run those models using the new version of ENMeval.  ENMevaluate objects created with ENMeval v 0.2.0 (and later versions) **do** have the slot for model objects and so you shouldn't get this error with those objects.  Hope that clears it up.
Bob

**Comment by elgabbas** [comment]
yes, I understand it like that. but is there a way to be able to access the old objects using the updated version of the package or I have to install a prior version instead?
Ahmed

**Comment by bobmuscarella** [comment]
Okay, I understand your question in two ways, let me try to answer both but let me know if I still don't get it...

1) You cannot access maxent model objects from ENMevaluate objects created with ENMeval versions before v 0.2.0 (they simply do not exist anymore).  You need to rerun ENMeval with a later version (after v 0.2.0) to access these.

2) Are you getting this error when simply trying to load 'old' ENMevaluate objects after installing a newer version of ENMeval?  You said that you get the error when using the ```str()``` function, which makes sense because the old ENMevaluate objects do not have a 'model' slot.  I tried this and get the same error when using ```str(old_ENMevaluate_object)``` and similar error if I do ```old_ENMevaluate_object@models```.  But, I can still access the other slots (e.g. results, predictions) from the old ENMevaluate objects without any problems.  

Hope this helps.

**Comment by elgabbas** [comment]
Thanks!
Yes, I can access individual slots (old_ENMevaluate_object@results, etc.) from the old model objects (using the updated version of the package). However, to make `str` function work, I have to use this command first `old_ENMevaluate_object@models <- list()` 
Ahmed

**Comment by bobmuscarella** [comment]
Yes, that makes sense.  Glad you got it cleared up.
