### ISSUE TITLE
NA's in AICc calculations

### ISSUE THREAD

**Issue by krypttr** [bobmuscarella/ENMeval#55]
Hi,

I am getting NA values for AICc calculations. Low number of occurence points (15). RMValues = 1, 2, 3, 4, 5. FC set to default. Method = jackknife. 1 categorical variable. What might be causing this? Should I accept the results as is?

![image](https://user-images.githubusercontent.com/7353461/40950933-84c1eeb4-687d-11e8-9511-4f3dd6526c28.png)

**Comment by bobmuscarella** [comment]
Hi -

The 'calc.aicc' function returns all NAs if the number of parameters is larger than the number of observations (occurrence localities).  This is mentioned in the documentation for that function.  I am pretty sure this is what's going on (especially since the more complex settings [i.e., more parameters] are the models that are NA for AICc).  You can check by looking at the results table and seeing if the number of parameters in the models built with those settings.  If the 'nparams' is > the number of your occurrence records (in your case, 15) then you should expect NAs.  For more details see the help for calc.aicc.

Hope it helps,
Bob

**Comment by krypttr** [comment]
Ah, it is in the calc.aicc functions help file. It escaped my notice. Investigating the lambda files, it is indeed the case. I have some questions regarding this but I guess maxent google group is more suitable for them. Thank you very much.
