### ISSUE TITLE
Type S4 Error for logistic output

### ISSUE THREAD

**Issue by simon-tarr** [bobmuscarella/ENMeval#64]
I'm having an issue plotting logistic maps from ENMeval::ENMevaluate() v0.3.0, having returned to the package after about 12 months to re-run part of an analysis. This code did run absolutely fine in the past, albeit with the original maxent.jar implementation.

When using predict() to plot the default raw output as logisitc I get the error:
`Error in newdata[, v] : object of type 'S4' is not subsettable`

I am running the following:

```
my.models<-ENMevaluate(occ=my.occ, env=expl, bg.coords = bckgnd, method='jackknife', defaultprevalence=prev, RMvalues=seq(1,5,0.5), fc=c("L", "LQ", "H", "LQH", "LQHP", "LQHPT"), parallel=TRUE)

log.output<-predict(my.models@models[[1]], expl)

`Error in newdata[, v] : object of type 'S4' is not subsettable`

```
To be clear, the ENMevaluate function runs fine using the above code. I just can't plot the logisitc output using predict(). I can't see anything immediately wrong with the above code, having trawled through the help files and online tutorial at https://cran.r-project.org/web/packages/ENMeval/vignettes/ENMeval-vignette.html. 

After getting the error I re-read the help file for the ENMevaluate function and saw that you can use the argument algorithm = "maxent.jar" to use the old method. When I flag this, the models run and I can use the predict() function as normal to generate a logisitc output.

I haven't been able to find out any information on the S4 error on the MaxEnt Google Group (although I did attempt to post yesterday - it hasn't appeared. Maybe a mod has to accept the question?). I therefore ask whether this is a bug or (more likely) -  am I doing something wrong?

If so, is there a recommended way of generating a logistic output in v0.3.0+ using the opensource version of MaxEnt and not maxent.jar? I note that generating a logisitc output is still listed as "coming soon" in the official tutorial I linked above so there doesn't seem to be too much help on best practise in this regard.

Thanks.

**Comment by bobmuscarella** [comment]
Hi Simon -

Yes, the error crops up because the current default of ENMevaluate uses the
'maxnet' algorithm and the output models are completely different beasts
compared to the output models using the 'maxent.jar' algorithm.  The
predict function does not work in the same way for the two model outputs.
We did create a function to predict with the maxnet model output (see:
https://github.com/bobmuscarella/ENMeval/blob/master/R/maxnet.predictRaster.R),
which might be helpful for you.  Jamie may also reply with some other
thoughts.

Hope this helps,
Bob

**Comment by simon-tarr** [comment]
Hi Bob,

Thanks for the speedy reply and explanation. I completely missed the maxnet.predictRaster() function somehow! Thanks for pointing it out. As as aside, is the function supposed to be called max**net**.predictRaster or should it be max**ent**.predictRaster?

I've got everything working with the old maxent.jar algo for now so there's no "emergency". I'll make sure I re-work my code for future projects to I'm using the nice open source versions.

Cheers,
Simon

**Comment by bobmuscarella** [comment]
Hi Simon -

You probably didn't see this function because we don't have documentation
for it since it works 'under the hood'.  Perhaps we should expose it to the
user for cases like this...  The function is named as we intended because
the regular 'predict' function from dismo works for the maxent models
output.  The maxnet output is what this is used for.

Hope this is clear and good luck with your work,
Bob

**Comment by simon-tarr** [comment]
Hi Bob, that all makes sense, thanks for the clarification! Happy for this issue to be closed but feel free to keep open if you and the team would like it here as a reminder to include this functionality somewhere in the documentation.

Cheers, Simon.

**Comment by ndimhypervol** [comment]
Just to let you know, we intend on making this an exported function for the future new release.
