### ISSUE TITLE
AICc with big number of parameters

### ISSUE THREAD

**Issue by andliszmmu** [bobmuscarella/ENMeval#82]
I run ENMeval with maxnet in order to evaluate AICc for model comparison. But get NAs always (instead of AICc). I found that "Returns all NAs if the number of parameters is larger than the number of observations (occurrence localities)." Well, what to do? It is a common situation. There should be some solution...

**Comment by ndimhypervol** [comment]
Especially with hinge features, the number of parameters (non-zero coefficients) can become quite inflated. Try making models without hinge features and see if AICc can be calculated.

**Comment by andliszmmu** [comment]
Thank you! I removed hinge features, but I have a lot of env. predictors. Yes, it is not the best idea to look for a model when number of occurrence points is below the number of raster predictors... But AIC should exist ))) It is not a measure of correctness of this kind, well?

> Especially with hinge features, the number of parameters (non-zero coefficients) can become quite inflated. Try making models without hinge features and see if AICc can be calculated.

**Comment by ndimhypervol** [comment]
From what I understand, when the number of model coefficients exceeds the number of data points, AIC should not be calculated. This is complicated for hinge features and other kinds of spline coefficients (i.e., GAM) because it's not clear how to treat them -- as coefficients equal in weight to non-hinge features, or weighted down in some way? There is no consensus, so we simply do not calculate AIC in these cases with ENMeval. For such models, you can use the cross validation results to guide you, as well as examining the response curves and spatial predictions.
